version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  mysql:
    image: mysql:5.7
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
       MYSQL_DATABASE: social_media_db
    ports:
      - "3307:3306"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"